[package]
name = "fruitmon"
version = "0.1.0"
authors = ["leslie"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "0.25.1"
#pixels = "0.0.2"
#serde = "1.0.103"
image = "0.22.3"
